import enum
import uuid
from datetime import datetime, timezone
from typing import Any, List, Optional
from sqlalchemy import DateTime, Enum, Float, ForeignKey, JSON, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class PaymentStatusEnum(str, enum.Enum):
    PENDING = "pending"
    VERIFIED = "verified"
    REJECTED = "rejected"


class PaymentRecord(Base):
    """Milestone invoice and bank verification record for a survey project."""
    __tablename__ = "payment_records"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    milestone_name: Mapped[str] = mapped_column(
        String(150),
        nullable=False
    )
    amount_usd: Mapped[float] = mapped_column(
        Float,
        nullable=False
    )
    status: Mapped[PaymentStatusEnum] = mapped_column(
        Enum(PaymentStatusEnum, name="payment_status_enum", create_type=False, values_callable=lambda obj: [e.value for e in obj]),
        default=PaymentStatusEnum.PENDING,
        nullable=False,
        index=True
    )
    payment_method: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True
    )
    reference_code: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        index=True
    )
    notes: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )
    slip_url: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )
    verified_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True
    )
    verified_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        nullable=False
    )


class Invoice(Base):
    """Digital billing invoice generated by Ops for a survey project with itemized cost lines."""
    __tablename__ = "invoices"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True
    )
    invoice_number: Mapped[str] = mapped_column(
        String(60),
        unique=True,
        index=True,
        nullable=False
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    client_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )
    title: Mapped[str] = mapped_column(
        String(200),
        default="Project Service Bill",
        nullable=False
    )
    bill_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False
    )
    due_date: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True
    )
    # List of JSON objects: [{sl_no: int, date: str, item_name: str, unit: float, price: float, tenure: str, total_price: float}]
    items: Mapped[Any] = mapped_column(
        JSON,
        default=list,
        nullable=False
    )
    subtotal_amount: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        nullable=False
    )
    total_amount: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        nullable=False
    )
    status: Mapped[str] = mapped_column(
        String(50),
        default="issued",
        nullable=False,
        index=True
    )
    notes: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )
    created_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )
